# Generated by Django 5.2.8 on 2025-12-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Ar da Sala', max_length=100)),
                ('device_id', models.CharField(help_text='ID único da placa (Ex: MAC Address ou Serial)', max_length=50, unique=True)),
                ('room', models.CharField(blank=True, max_length=100)),
                ('brand', models.CharField(default='Samsung', help_text='Marca do Ar-Condicionado (ex: Samsung, LG, Fujitsu)', max_length=50)),
                ('model', models.CharField(blank=True, help_text='Modelo específico (opcional)', max_length=50, null=True)),
                ('wifi_ssid', models.CharField(blank=True, max_length=100, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('power', models.BooleanField(default=False)),
                ('temperature', models.IntegerField(default=24)),
                ('mode', models.CharField(default='cool', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
