# Generated by Django 6.0.2 on 2026-03-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('room', models.CharField(max_length=50)),
                ('brand', models.CharField(choices=[('Carrier', 'Carrier'), ('Midea', 'Midea'), ('Springer', 'Springer'), ('Fujitsu', 'Fujitsu'), ('Samsung', 'Samsung'), ('LG', 'LG'), ('Daikin', 'Daikin'), ('Consul', 'Consul'), ('Elgin', 'Elgin'), ('Gree', 'Gree'), ('generic', 'Genérico')], default='Carrier', max_length=20)),
                ('wifi_ssid', models.CharField(blank=True, max_length=100, null=True)),
                ('wifi_password', models.CharField(blank=True, max_length=100, null=True)),
                ('is_configured', models.BooleanField(default=False)),
                ('is_online', models.BooleanField(default=False)),
                ('is_registered', models.BooleanField(default=True)),
                ('power', models.BooleanField(default=False)),
                ('temperature', models.IntegerField(default=24)),
                ('mode', models.CharField(choices=[('cool', 'Resfriar'), ('heat', 'Aquecer'), ('fan', 'Ventilar'), ('dry', 'Desumidificar'), ('auto', 'Automático')], default='cool', max_length=10)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('last_command', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
                'ordering': ['-is_online', 'name'],
            },
        ),
    ]
