# Generated by Django 5.2.8 on 2025-12-09 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['-is_online', 'name']},
        ),
    ]
