# Generated by Django 5.2.8 on 2025-12-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_device_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['-is_online', 'name'], 'verbose_name': 'Dispositivo', 'verbose_name_plural': 'Dispositivos'},
        ),
        migrations.RemoveField(
            model_name='device',
            name='model',
        ),
        migrations.AddField(
            model_name='device',
            name='is_configured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='is_registered',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='device',
            name='last_command',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='wifi_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='brand',
            field=models.CharField(choices=[('Carrier', 'Carrier'), ('Midea', 'Midea'), ('Springer', 'Springer'), ('Fujitsu', 'Fujitsu'), ('Samsung', 'Samsung'), ('LG', 'LG'), ('Daikin', 'Daikin'), ('Consul', 'Consul'), ('Elgin', 'Elgin'), ('Gree', 'Gree'), ('generic', 'Genérico')], default='Carrier', max_length=20),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='mode',
            field=models.CharField(choices=[('cool', 'Resfriar'), ('heat', 'Aquecer'), ('fan', 'Ventilar'), ('dry', 'Desumidificar'), ('auto', 'Automático')], default='cool', max_length=10),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='room',
            field=models.CharField(max_length=50),
        ),
    ]
