# Generated by Django 6.0.2 on 2026-03-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_device_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
    ]
